config/routes.rb
BeheldV2::Application.routes.draw do
  
  devise_for :views

  devise_for :users

  root :to => 'pages#home'
  
  get 'menu' => 'pages#menu'

  get 'search' => 'pages#search'
  
  get 'price_search_results' => 'pages#price_search_results'
  
  get 'artist_search_results' => 'pages#artist_search_results'
  
  get 'gallery_search_results' => 'pages#gallery_search_results'
  
  get 'learn' => 'pages#learn'
  
  get 'blog' => 'pages#blog'
  
  get 'legal' => 'pages#legal'
  
  get 'selection' => 'pages#selection'
  
  get 'review' => 'pages#review'
  
  get 'shipping' => 'pages#shipping'
  
  get 'payment' => 'pages#payment'
  
  get 'success_payment' => 'pages#success_payment'
  
  get 'user_profile' => 'pages#user_profile'
   
  get 'artist_profile' => 'pages#artist_profile'
  
  get 'gallery_profile' => 'pages#gallery_profile'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 def home
  end

  def menu
  end

  def search
  end
  
  def search_results
  end
  
  def legal
  end
  
  def selection
  end
  
  def review
  end
  
  def shipping
  end
  
  def payment
  end
  
  def success_payment
  end
  
  def legal
  end
  
  def user_profile
  end
  
  def artist_profile
  end
  
  def artist_search_results
  end
  
  def gallery_profile
  end
  
  def gallery_search_results
  end
  
  def price_search_results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_banner.html.erb
<img class="banner-img" src="/images/gallery1.jpg" />
 	 <div class="banner-text">
	 	 <h1 class="banner-header"><strong>Welcome to Beheld!</strong></h1>
	 	 	<%= link_to "Sign Up", selection_path, class: "btn btn-danger btn-large" %>
	 </div>

app/views/layouts/_footer.html.erb
		<div class="container navbar-inverse footer">
				<ul class="navbar-nav pull-left">
					<strong><%= link_to "Facebook", "#", class: "social-link1" %></strong>
					<strong><%= link_to "Twitter", "#", class: "social-link" %></strong>
					<strong><%= link_to "Pinterest", "#", class: "social-link" %></strong>
					<strong><%= link_to "Legal", legal_path, class: "social-link" %></strong>
					<a href="mailto:info@beheld.me?Subject=Website%20Contact" target="_top" class="social-link"><strong>Contact</strong></a>
				</ul>
				<ul class="nav pull-right">
					<p class="copyright">&copy; 2013 All rights reserved by beheld.me</p>
				</ul>
		</div>	

app/views/layouts/_header.html.erb
<div class="container">	
	<div class="codrops-top clearfix">
		<span>
			<a>BEHELD</a>
		</span>
		<span class="right">
			<a>MENU</a>
		</span>
	</div>
</div>
	
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
  <title>Beheld - Online Art Gallery | Tool for Artists</title>
  	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
	  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	  	<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="description" content="Beheld is a community of Artists, Galleries and Buyers." />		
		<meta name="keywords" content="Art | Original Art | Artists | Business Tool | Gallery | Galleries" />
</head>
<body class="container">

	<%= render 'layouts/header' %>
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>

			<%= yield %>
			
	<%= render 'layouts/footer' %>

	<script src="../../assets/javascripts/jquery.js"></script>
	<script src="../../assets/javascripts/bootstrap.js"></script>
	<script src="../../assets/javascripts/boxlayout.js"></script>
	<script>
		$(document).ready(function(){
			$('.carousel').carousel()
		});
	</script>
</div>
</body>
</html>

app/views/pages/_about.html.erb
						<h2>What is Beheld?</h2>
						<p>
		Beheld is the ultimate online tool for Artists. Our platform allows Artist to post, sell and ship their art all over the planet. The road to becoming a professional artist is not easy which is why we are laser focused on supporting the up and coming artist. This provides a unique experience for buyers. 
	</p>
<h2>How does it work?</h2>
	<p>
		Beheld provides all the tools needed for an independent artist to be successful.
	</p>
<!-- TEAM -->
	<h1 class="page-header">The Team</h1>
		<div class="row">
<!-- BILL -->
			<div class="col-lg-3">
					<div class="thumbnail">
						<img class="about-profile-img" src="/images/bill.jpg" />
							<div class="caption">
								<h3>Bill Higginson</h3>
								<h5>Co-founder</h5>
									<p> 
										<a data-toggle="modal" href="#bill-bio" class="btn btn-primary bio-btn btn-block">Bio</a>
									</p>
							</div>
					</div>
			</div>
<!-- MODAL -->
  			<div class="modal fade" id="bill-bio">
	  				<div class="modal-dialog">
		  					<div class="modal-content">
			  						<div class="modal-header">
				  							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				  								<h4 class="modal-title">Bill Higginson's Bio</h4>
				  								<h5>Co-founder</h5>
				  					</div>
				  					<div class="modal-body">
					  					<p>Bill has been an artist all his life but a professional artist for 5 years. Bill is highly recognized in the Vancouver arts community sitting on the board of the FOCA and doing many teaching and speaking series.</p>
				  					</div>
				  					<div class="modal-footer">
					  						<button type="button" class="close btn btn-info" data-dismiss="modal" aria-hidden="true">Close</button>
					  				</div>
					  		</div>
					</div>
			</div>
<!-- Colin -->
			<div class="col-lg-3">
					<div class="thumbnail">
						<img class="about-profile-img" src="/images/colin.jpg" />
							<div class="caption">
								<h3>Colin Brown</h3>
								<h5>Co-founder</h5>
									<p> 
										<a data-toggle="modal" href="#colin-bio" class="btn btn-primary bio-btn btn-block">Bio</a>
									</p>
							</div>
					</div>
			</div>
<!-- MODAL -->
  			<div class="modal fade" id="colin-bio">
	  				<div class="modal-dialog">
		  					<div class="modal-content">
			  						<div class="modal-header">
				  							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				  								<h4 class="modal-title">Colin Brown's Bio</h4>
				  								<h5>Co-founder</h5>
				  					</div>
				  					<div class="modal-body">
					  					<p> Colin is a massive nerd! He has been on the business end of technology for the 4 years working solely with startups. 
				  					</div>
				  					<div class="modal-footer">
					  						<button type="button" class="close btn btn-info" data-dismiss="modal" aria-hidden="true">Close</button>
					  				</div>
					  		</div>
					</div>
			</div>
		</div>

app/views/pages/_search.html.erb
<h2>Search</h2>
<fieldset>
	<p>All search fields are optional. Select only what is important to you.</p>
	<div class="form-group">
		<label>Search by Medium</label>
			<select class="form-control">
				<option>Select a Medium</option>	
				<option>Oil Paintings</option> 
				<option>Acrylic Paintings</option>
				<option>Watercolours</option> 
				<option>Pastels</option> 
				<option>Drawings</option> 
				<option>Graphite</option>
				<option>Mixed Media</option> 
				<option>Photographic</option> 
				<option>Other</option>
			</select>
	</div>	
	<div class="form-group">
		<label>Search by Genre</label>
			<select class="form-control">
				<option>Select a Genre</option>
				<option>Abstract</option> 
				<option>Contemporary</option>
				<option>Figurative</option> 
				<option>Pop Art</option> 
				<option>Portraiture</option> 
				<option>Realism</option>
				<option>Street Art</option> 
				<option>Surrealist</option>
				<option>Fantasy</option>
				<option>Other</option>
			</select>
	</div>
	<div class="form-group">
		<label>Search by Subject Matter</label>
			<select class="form-control">
				<option>Select a Subject Matter</option>
				<option>Landscape</option>
				<option>Architecture</option> 
				<option>Botanical</option>
				<option>Figurative</option>
				<option>Still Life</option>
				<option>Graphic</option> 
				<option>Animals/wildlife</option>
				<option>Other</option>				
			</select>
	</div>
	<div class="form-group">
		<label>Search by Size</label>
			<select class="form-control">
				<option>Select a Height (inches)</option>
				<option>10'</option>
				<option>11'</option> 
				<option>12'</option>
				<option>13'</option>
				<option>14'</option>
				<option>15'</option> 
				<option>16'</option>
				<option>17'</option>	
				<option>18'</option>
				<option>19'</option>
				<option>20'</option>
				<option>21'</option>
				<option>22'</option>
				<option>23'</option>
				<option>24'</option>
				<option>25'</option>
				<option>26'</option>
				<option>27'</option>
				<option>28'</option>
				<option>29'</option>
				<option>30'</option>
				<option>31'</option>
				<option>32'</option>
				<option>33'</option>
				<option>34'</option>
				<option>35'</option>
				<option>36'</option>
				<option>37'</option>
				<option>38'</option>
				<option>39'</option>
				<option>40'</option>
				<option>41'</option>
				<option>42'</option>
				<option>43'</option>
				<option>44'</option>
				<option>45'</option>
				<option>46'</option>
				<option>47'</option>
				<option>48'</option>
				<option>49'</option>
				<option>50'</option>		
			</select>
			<select class="form-control">
				<option>Select a Width (inches)</option>
				<option>10'</option>
				<option>11'</option> 
				<option>12'</option>
				<option>13'</option>
				<option>14'</option>
				<option>15'</option> 
				<option>16'</option>
				<option>17'</option>	
				<option>18'</option>
				<option>19'</option>
				<option>20'</option>
				<option>21'</option>
				<option>22'</option>
				<option>23'</option>
				<option>24'</option>
				<option>25'</option>
				<option>26'</option>
				<option>27'</option>
				<option>28'</option>
				<option>29'</option>
				<option>30'</option>
				<option>31'</option>
				<option>32'</option>
				<option>33'</option>
				<option>34'</option>
				<option>35'</option>
				<option>36'</option>
				<option>37'</option>
				<option>38'</option>
				<option>39'</option>
				<option>40'</option>
				<option>41'</option>
				<option>42'</option>
				<option>43'</option>
				<option>44'</option>
				<option>45'</option>
				<option>46'</option>
				<option>47'</option>
				<option>48'</option>
				<option>49'</option>
				<option>50'</option>				
			</select>
	</div>
	<div class="form-group">
		<label>Search by Price</label>
			<input type="text" class="form-control" placeholder="ex. $500">
	</div>
		<%= link_to "All Art", price_search_results_path, class: "btn btn-primary" %>
		<%= link_to "Search", price_search_results_path, class: "btn btn-danger" %>
</fieldset>

<fieldset>
	<div class="form-group">
		<label>Search for Artist</label>
			<input type="text" class="form-control" placeholder="ex. Joe Smith">
	</div>
		<%= link_to "All Artists", artist_search_results_path, class: "btn btn-primary" %>
		<%= link_to "Search", artist_search_results_path, class: "btn btn-danger" %>
</fieldset>

<fieldset>
	<div class="form-group">
		<label for="first-name">Search for Gallery</label>
			<input type="text" class="form-control" id="first-name" placeholder="ex. Westside Gallery">
	</div>
		<%= link_to "All Galleries", gallery_search_results_path, class: "btn btn-primary" %>
		<%= link_to "Search", gallery_search_results_path, class: "btn btn-danger" %>
</fieldset>

app/views/pages/_selection.html.erb
<h2>Sign Up</h2>
<div class="row text-center">
		<div class="col-lg-4 buyer-col">
			<div class="thumbnail">
				<h3>Buyer</h3>
					<p>
						Welcome to the art world connected! Our community of artist and galleries are excited to present their work to you. Our platform allows you to discover, track and buy art from all over the world.
					</p>
						<div class="caption">
							<h5>Price: FREE FOR LIFE!</h5><br>
								<h5>What you get:</h5>
									<p>
										<h6>Access to a community of artists and galleries</h6>
										<h6>Track specific artists</h6>											
										<h6>Chose to be anonymous or known to the artist</h6>											
										<h6>Find new exciting artists</h6>
										<h6>Easily purchase art and have it delivered right to your door.</h6>
									</p>
									<br>
									<p>
										<%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-block btn-large btn-danger" %>
									</p>
						</div>
			</div>
		</div>
		<div class="col-lg-4 artist-col">
			<div class="thumbnail">
				<h3 class="text-center">Artist</h3>
					<p>
						The hardest thing about being an artist is making a living off of being an artist. Let us do the heavy lifting for you. Our platform gives you an online presence, access to a community of buyers, and we handle all the details like shipping and payment. 
					</p>
					<div class="caption">
						<div class="caption">
							<h5>Price: 20% of Art Sales</h5><br>
								<h5>What you get:</h5>
									<p>
										<h6>Access to a community of Buyers</h6>									
										<h6>Your own website to promote your work</h6>
										<h6>Easily communicate with your followers</h6>
										<h6>We handle the transaction</h6>
										<h6>We handle the shipping</h6>
										<br>
										<strong>You get to be an artist and let us worry about the business details.</strong>
									</p>
									<p>
										<%= link_to "Request Access", "#", class: "btn btn-block btn-large btn-danger" %>
									</p>
						</div>
					</div>
			</div>
	</div>
		<div class="col-lg-4 buyer-col">
			<div class="thumbnail">
				<h3>Gallery</h3>
					<p>
						Bring your gallery online.
					</p>
						<div class="caption">
							<h5>Price: $100 per month + 4% of sales</h5><br>
								<h5>What you get:</h5>
									<p>
										<h6>Access to a community of artists and galleries</h6>
										<h6>Track specific artists</h6>											
										<h6>Chose to be anonymous or known to the artist</h6>											
										<h6>Find new exciting artists</h6>
										<h6>Easily purchase art and have it delivered right to your door.</h6>
									</p>
									<br>
									<p>
										<%= link_to "Request Access", "#", class: "btn btn-block btn-large btn-danger" %>
									</p>
						</div>
			</div>
		</div>
	</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<h2>All Artwork</h2>
		<div id="carousel1" class="carousel slide">
	  		<div class="carousel-inner">
		  			<div class="item active">
			  				<img class="carousel-img" src="/images/Pic1.jpg" />
			  					<div class="pull-left carousel-des">
			  						<h4>Bill Higginson</h4>
			  					</div>
			  					<div class="pull-right carousel-des">
			  						<h3>Price: <strong>$1,000</strong></h3>
			  					</div>
					</div>
					<div class="item">
			  				<img class="carousel-img" src="/images/Pic2.jpg" />
			  					<div class="pull-left carousel-des">
			  						<h4>Bill Higginson</h4>
			  					</div>
			  					<div class="pull-right carousel-des">
			  						<h3>Price: <strong>$1,000</strong></h3>
			  					</div>
					</div>
					<div class="item">
			  				<img class="carousel-img" src="/images/Pic3.jpg" />
			  					<div class="pull-left carousel-des">
			  						<h4>Bill Higginson</h4>
			  					</div>
			  					<div class="pull-right carousel-des">
			  						<h3>Price: <strong>$1,000</strong></h3>
			  					</div>
					</div>
			</div>
			
			<a class="left carousel-control" href="#carousel1" data-slide="prev">
					<span class="icon-prev"></span>
			</a>
			<a class="right carousel-control" href="#carousel1" data-slide="next">
					<span class="icon-next"></span>
			</a>
		</div>
		<br>
		<%= link_to "Buy It", review_path, class: "btn btn-block btn-danger buy-btn" %>
		<%= link_to "Gallery View", root_path, class: "btn btn-block btn-default buy-btn" %>
<% else %>
	<%= render 'layouts/banner' %>
<% end %>
	

app/views/pages/menu.html.erb
<div id="bl-main" class="bl-main">
<!-- About -->
		<section>
				<div class="bl-box">
						<h2 class="bl-icon bl-icon-about">About</h2>
				</div>
				<div class="bl-content">
						<%= render 'pages/about' %>		
						<span class="bl-icon bl-icon-close"></span>
		</section>
<!-- Search -->		
		<section id="bl-work-section">
				<div class="bl-box">
						<h2 class="bl-icon bl-icon-works">Search</h2>
				</div>
				<div class="bl-content">
						<%= render 'pages/search' %>						
						<span class="bl-icon bl-icon-close"></span>
		</section>
<!-- Blog -->		
		<section>
			<a>
				<div class="bl-box">
						<h2 class="bl-icon bl-icon-blog">Blog</h2>
				</div>
			</a>
		</section>
<!-- Learning -->
		<section>
				<div class="bl-box">
						<h2 class="bl-icon bl-icon-contact">Learning</h2>
				</div>
				<div class="bl-content">
						<h2>Learning Center</h2>
						<p>Coming Soon...</p>
				</div>
				<span class="bl-icon bl-icon-close"></span>
		</section>
<% if user_signed_in? %>
<!-- Profile -->		
		<section>
				<!-- need code to link to the appropriate profile -->
				<a>
						<div class="bl-box">
								<h2 class="bl-icon bl-icon-contact">Login</h2>
						</div>
				</a>
		</section>
<!-- Logout -->
		<section>
				<a>
						<div class="bl-box">
								<h2 class="bl-icon bl-icon-contact">Login</h2>
						</div>
				</a>
		</section>
<% else %>
<!-- Sign Up -->		
		<section>
				<div class="bl-box">
						<h2 class="bl-icon bl-icon-contact">Sign Up</h2>
				</div>
				<div class="bl-content">
						<%= render 'pages/selection' %>
						<span class="bl-icon bl-icon-close"></span>
		</section>
<!-- Login -->
		<section>
				<a>
						<div class="bl-box">
								<h2 class="bl-icon bl-icon-contact">Login</h2>
						</div>
				</a>
		</section>
<% end %>

app/views/pages/user_profile.html.erb
<h1 class="page-header">User Name's Profile</h1>
		<div class="row">
			<div class="col-lg-4">
				<img class="artist-img" src="/images/colin.jpg" />	
			</div>
			<div class="col-lg-4">
				<h4>Profile Information</h4>
					<p>Colin</p>
					<p>Brown</p>
					<p>Email: colin.scott.brown@gmail.com</p>
					<p>Password: **********</p>
					<p><strong>Shipping Address:</strong></p>
					<p>309-788 Hamilton Street</p>
					<p>Vancouver, BC, Canada</p>
					<p>V6B0E9</p>
				<%= link_to "Edit Profile", "#", class: "btn btn-block btn-primary" %>
				<%= link_to "Cancel Account", "#", class: "btn btn-block btn-default" %>
			</div>
			<div class="media col-lg-4 row">
				<h4>Who you are following:</h4>
					<div class="media">
						<div class="media-body">
							<h5 class="media-heading">Artist's Name</h5>
								<%= link_to "Profile", artist_profile_path, class: "btn btn-danger" %>
								<%= link_to "Follow", artist_profile_path, class: "btn btn-primary" %>
						</div>
					</div>
					<div class="media">
						<div class="media-body">
							<h5 class="media-heading">Artist's Name</h5>
								<%= link_to "Profile", artist_profile_path, class: "btn btn-danger" %>
								<%= link_to "Follow", artist_profile_path, class: "btn btn-primary" %>
						</div>
					</div>
					<div class="media">
						<div class="media-body">
							<h5 class="media-heading">Artist's Name</h5>
								<%= link_to "Profile", artist_profile_path, class: "btn btn-danger" %>
								<%= link_to "Follow", artist_profile_path, class: "btn btn-primary" %>
						</div>
					</div>
					<div class="media">
						<div class="media-body">
							<h5 class="media-heading">Artist's Name</h5>
								<%= link_to "Profile", artist_profile_path, class: "btn btn-danger" %>
								<%= link_to "Follow", artist_profile_path, class: "btn btn-primary" %>
						</div>
					</div>
					<br><a>See Next 4...</a>
			</div>
	</div>
	<br>
	<h1 class="page-header">Purchases</h1>
		<div id="carousel1" class="carousel slide">
	  		<div class="carousel-inner">
		  			<div class="item active">
			  				<img class="carousel-img" src="/images/Pic1.jpg" />
			  					<div class="pull-left carousel-des">
			  						<h4>Bill Higginson</h4>
			  					</div>
			  					<div class="pull-right carousel-des">
			  						<h3>Price: <strong>$1,000</strong></h3>
			  					</div>
					</div>
					<div class="item">
			  				<img class="carousel-img" src="/images/Pic2.jpg" />
			  					<div class="pull-left carousel-des">
			  						<h4>Bill Higginson</h4>
			  					</div>
			  					<div class="pull-right carousel-des">
			  						<h3>Price: <strong>$1,000</strong></h3>
			  					</div>
					</div>
					<div class="item">
			  				<img class="carousel-img" src="/images/Pic3.jpg" />
			  					<div class="pull-left carousel-des">
			  						<h4>Bill Higginson</h4>
			  					</div>
			  					<div class="pull-right carousel-des">
			  						<h3>Price: <strong>$1,000</strong></h3>
			  					</div>
					</div>
			</div>
			
			<a class="left carousel-control" href="#carousel1" data-slide="prev">
					<span class="icon-prev"></span>
			</a>
			<a class="right carousel-control" href="#carousel1" data-slide="next">
					<span class="icon-next"></span>
			</a>
		</div>
		<br>